---
title: "WGCNA"
output: 
  pdf_document: default
params:
  
---

```{r}
library(WGCNA)
options(stringsAsFactors = FALSE)
```


```{r}
data = read.csv("..\\WGCNA_tutorial\\FemaleLiver-Data\\LiverFemale3600.csv")
dim(data)
names(data)
```

```{r}
dat0 = as.data.frame(t(data[, -c(1:8)]))
names(dat0) = data$substanceBXH
rownames(dat0) = names(data)[-c(1:8)]
dat0
```

```{r}
gsg = goodSamplesGenes(dat0, verbose = 3)
gsg$allOK
```

```{r}
if(!gsg$allOK){
  if(sum(!gsg$goodGenes) > 0)
    printFlush(paste("Removing genes:", paste(names(dat0)[!gsg$goodGenes], collapse = ", ")))
  if(sum(!gsg$goodSamples>0))
    printFlush(paste("Removing samples:", paste(rownames(dat0)[!gsg$goodSamples], collapse = ", ")))
  dat0 = dat0[gsg$goodSamples, gsg$goodGenes]
}
```

```{r}
sampleTree = hclust(dist(dat0), method = "average")
par(cex = 0.6)
par(mar = c(0,4,2,0))
plot(sampleTree, main = "Sample clustering to detect outliers", sub = "", xlab = "", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
```

```{r}
clust = cutreeStatic(sampleTree, cutHeight = 15, minSize = 10)
table(clust)

```

```{r}
#clust 1 contains the samples we want to keep
keepSamples = (clust == 1)
datExpr = dat0[keepSamples, ]
nGenes = ncol(datExpr)
nSamples = nrow(datExpr)
datExpr
```

```{r}
traits = read.csv("..\\WGCNA_tutorial\\FemaleLiver-Data\\ClinicalTraits.csv")
dim(traits)
names(traits)

#get rid of unneeded columns
allTraits = traits[, -c(31,16)]
allTraits = allTraits[, c(2, 11:36)]
dim(allTraits)
names(allTraits)

fs = rownames(datExpr)
traitRows = match(fs, allTraits$Mice)
datTraits = allTraits[traitRows, -1]
rownames(datTraits) = allTraits[traitRows, 1]

collectGarbage()
datTraits
```

```{r}
#visualization of clinical traits relation to sample dendrogram

sampleTree2 = hclust(dist(datExpr), method = "average")
traitColors = numbers2colors(datTraits, signed = FALSE)
plotDendroAndColors(sampleTree2, traitColors, groupLabels = names(datTraits), main = "Sample dendrogram and heatmap")
```


#network construction and module detection

```{r}
#choose set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))

#call the network topology analysis function
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 5)

#sizeGrWindow(9,5)
par(mfrow = c(1,2))
cex1 = 0.9

#scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab = "Soft Threshold (power)", ylab = "Scale Free Topology Model Fit,signed R^2", type = "n", main = paste("Scale independence"))

text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels = powers, cex = cex1, col = "red")

#this line corresponds to using an R^2 cut-off of h
abline(h=0.90, col= "red")

#mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab = "Soft Threshold (power)", ylab = "Mean connectivity", type = "n", main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels = powers, cex = cex1, col = "red")
```

```{r}
#construct gene networks and identify modules
net = blockwiseModules(datExpr, power = 6, TOMType = "unsigned", minModuleSize = 30, reassignThreshold = 0, mergeCutHeight = 0.25, numericLabels = TRUE, pamRespectsDendro = FALSE, verbose = 3)
```

```{r}
#how many modules there are and how many genes they contain in descending order. Module 0 is the genes that didn't fit into any of the other modules (the leftover ones)
table(net$colors)
```

```{r}
sizeGrWindow(12,9)
mergedColors = labels2colors(net$colors)
plotDendroAndColors(net$dendrograms[[1]], mergedColors[net$blockGenes[[1]]], "Module colors", dendroLabels = FALSE, hang = 0.03, addGuide = TRUE, guideHang = 0.05)
```

```{r}
moduleLabels = net$colors
moduleColors = labels2colors(net$colors)
MEs = net$MEs
geneTree = net$dendrograms[[1]]
```

#Relating modules to external info and identifying important genes

```{r}
#Recalculate MEs with color labels
MEs = moduleEigengenes(datExpr, moduleColors)$eigengenes
MEs = orderMEs(MEs)
moduleTraitCor = cor(MEs, datTraits, use = "p")
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples)
```

```{r}
#graphical representation
textMatrix = paste(signif(moduleTraitCor, 2), "\n(", signif(moduleTraitPvalue, 1), ")", sep = "")
dim(textMatrix) = dim(moduleTraitCor)
par(mar = c(6, 8.5, 3, 3))

#display correlation values within a heatmap
labeledHeatmap(Matrix = moduleTraitCor, xLabels = names(datTraits), yLabels = names(MEs), ySymbols = names(MEs), colorLabels = FALSE, colors = greenWhiteRed(50), textMatrix = textMatrix, setStdMargins = FALSE, cex.text = 0.5, zlim = c(-1,1), main = paste("Module-trait relationships"))
```

```{r}
weight = as.data.frame(datTraits$weight_g)
names(weight) = "weight"
#names (colors) of the modules
modNames = substring(names(MEs), 3)

geneModuleMembership = as.data.frame(cor(datExpr, MEs, use = "p"))
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples))

names(geneModuleMembership) = paste("MM", modNames, sep = "")
names(MMPvalue) = paste("p.MM", modNames, sep = "")

geneTraitSignificance = as.data.frame(cor(datExpr, weight, use = "p"))
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples))

names(geneTraitSignificance) = paste("GS.", names(weight), sep = "")
names(GSPvalue) = paste("p.GS", names(weight), sep = "")

```

```{r}
#Intramodular analysis: identifying genes with high GS and MM
#looking at brown module
module = "brown"
column = match(module, modNames)
moduleGenes = moduleColors == module

sizeGrWindow(7,7)
par(mfrow = c(1,1))
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]), abs(geneTraitSignificance[moduleGenes, 1]), xlab = paste("Module Membership in", module, "module"), ylab = "Gene significance for body weight", main = paste("Module membership vs gene significance\n"), cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)

```

```{r}
#summary output of network analysis results
annot = read.csv("..\\WGCNA_tutorial\\FemaleLiver-Data\\GeneAnnotation.csv")
dim(annot)
names(annot)
probes = names(datExpr)
probes2annot = match(probes, annot$substanceBXH)
#number of probes without annotation
sum(is.na(probes2annot))
#if all have annotation, should return 0
```

```{r}
geneInfo = data.frame(substanceBXH = probes, geneSymbol = annot$gene_symbol[probes2annot], LocusLinkID = annot$LocusLinkID[probes2annot], moduleColor = moduleColors, geneTraitSignificance, GSPvalue)
#order modules by significance for weight
modOrder = order(-abs(cor(MEs, weight, use = "p")))
#add module membership info in the chosen order
for(mod in 1:ncol(geneModuleMembership)){
  oldNames = names(geneInfo)
  geneInfo = data.frame(geneInfo, geneModuleMembership[, modOrder[mod]], MMPvalue[, modOrder[mod]])
  names(geneInfo) = c(oldNames, paste("MM.", modNames[modOrder[mod]], sep = ""), paste("p.MM", modNames[modOrder[mod]], sep = ""))
}

#order the genes in geneInfo first by module color, then by geneTraitSignificance
geneOrder = order(geneInfo$moduleColor, -abs(geneInfo$GS.weight))
geneInfo = geneInfo[geneOrder, ]
```

```{r}
fix(geneInfo)
```


#Network visualization using WGCNA functions
```{r}
#this chunk may take a while
dissTOM = 1-TOMsimilarityFromExpr(datExpr, power = 6)
plotTOM = dissTom^7
diag(plotTOM) = NA
sizeGrWindow(9,9)
TOMplot(plotTOM, geneTree, moduleColors, main = "Network heatmap plot, all genes")
```

```{r}
#visualizing the network of eigengenes

#recalculate module eigengenes
MEs = moduleEigengenes(datExpr, moduleColors)$eigengenes

#Isolate wanted physiological traits from the trait dataframe
weight = as.data.frame(datTraits$weight_g)
names(weight) = "weight"

#add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs, weight))
sizeGrWindow(5, 7.5)
par(cex = 0.9)
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle = 90)
#plot the dendrogram
sizeGrWindow(6,6)
par(cex = 1.0)
plotEigengeneNetworks(MET, "Eigengene dendrogram", marDendro = c(0,4,2,0), plotHeatmaps = FALSE)
```


```{r}
#plot the heatmap matrix
par(cex = 1.0)
plotEigengeneNetworks(MET, "Eigengene adjancency heatmap", marHeatmap = c(3,4,2,2), plotDendrograms = FALSE, xLabelsAngle = 90)
```












